#!/usr/bin/env bash
# a05-hunt-slot.sh — one bounded blind-transit hunt per loam interleave slot (3/9/15/21).
#
# Driven by `windowsill-hunt.timer` (systemd --user, 03/09/15/21:02 local). The
# runner (scripts/a05_hunt.py) owns the search, the checkpoints, the receipt and
# the grading; this wrapper owns only the git side: stage what the runner wrote,
# push it if and only if it graded, and leave the clone exactly as it found it.
#
# Contract: handoffs/2026-08-14-win-to-loam-a05-sector-split.md (loam = sectors 3, 30).
# Sector comes from $LAB/hunt.sector; stop with `touch $LAB/hunt.stop`.
#
# It lived unversioned in ~/.lab/ until 2026-08-18, which is how a stale glob in it
# went unnoticed for days (see THE STAGING RULE below). It sits beside campaign.sh
# now, under the same tests as the rest of the instrument.
#
# Config (env) — all three are test seams, defaulted to this box's real paths:
#   LAB_HUNT_LAB   runtime dir holding hunt.sector / hunt.stop / the logs  (~/.lab)
#   LAB_HUNT_REPO  the windowsill-lab clone to publish from
#   LAB_HUNT_PY    the interpreter that runs the hunt driver
set -u
shopt -s nullglob   # an absent dossier must vanish from the `git add` list, not
                    # reach git as a literal unexpanded glob

LAB="${LAB_HUNT_LAB:-$HOME/.lab}"
REPO="${LAB_HUNT_REPO:-$HOME/projects/windowsill-lab}"
PY="${LAB_HUNT_PY:-$REPO/.venv/bin/python}"

[ -e "$LAB/hunt.stop" ] && exit 0
exec 9>"$LAB/hunt.lock"
flock -n 9 || exit 0   # a hunt is already running — one hunt per slot per box

sector=$(cat "$LAB/hunt.sector" 2>/dev/null || echo 3)
log="$LAB/hunt-s${sector}-$(date +%F).log"

cd "$REPO" || exit 1

# THE POT RULE. pot.json's hunt block is a pure function of the receipts, and CI
# enforces `pot == hunt_block()` — so a receipt committed WITHOUT its refreshed pot
# ships a red main in the producer's own commit (the 2026-08-15 nightly did that),
# and a pot left dirty by a run we do NOT commit halts the physics lane: campaign.sh
# refuses to run against a dirty tracked file, which quietly ate campaign passes
# 119-124, ~33h, on 2026-08-17/18 with both units green. So the two paths differ:
# a pushed receipt takes pot.json WITH it, and any other exit restores pot.json.
restore_pot(){
  git diff --quiet -- pot.json 2>/dev/null && return 0
  git checkout -- pot.json 2>>"$log" \
    && echo "$(date -Is) pot.json restored — nothing of this run is being published" >>"$log"
}

# An ungraded receipt may not sit in reports/hunts/. The aggregator globs that
# DIRECTORY, not git (src/lab/publish.py), so a receipt left there is counted into
# the public ledger by the next run that publishes — while CI, which only ever sees
# the committed set, recomputes a different total and goes red. Filing it beside its
# log is what win's contract already says ("stays local with the log"); it keeps the
# evidence and keeps it out of the counters.
# COST, eyes open: already_searched() globs the same directory, so a quarantined
# run's targets become eligible again and a later slot may re-search them.
quarantine_receipt(){
  [ -n "${receipt:-}" ] && [ -f "$receipt" ] || return 0
  # The runner quarantines its own ungraded receipts and PRINTS the settled path,
  # so the path read back may already be the filed one — never move a file onto
  # itself.
  case "$receipt" in "$LAB/ungraded/"*) return 0 ;; esac
  mkdir -p "$LAB/ungraded" || return 1
  # A lead's dossier is cited by the receipt that ships it, so it travels into
  # quarantine for the same reason it travels into git — together or not at all.
  local dossiers stem_name
  stem_name="$(basename "$receipt" .json)"
  dossiers="$(dirname "$receipt")/dossiers"
  for rendered in "$dossiers/$stem_name"-tic*.html; do
    mv -f "$rendered" "$LAB/ungraded/" 2>>"$log"
  done
  mv -f "$receipt" "$LAB/ungraded/" \
    && echo "$(date -Is) ungraded receipt filed with the log -> $LAB/ungraded/$(basename "$receipt")" >>"$log"
}

# A conflicted `git pull --rebase` leaves the clone DETACHED and mid-rebase. Both
# calls here used to discard the status (`-q 2>>"$log"` and `>>"$log" 2>&1`), so the
# strand was invisible: the 100-minute hunt burned against an unsynced clone, its
# commit landed on detached HEAD, the push silently failed and the receipt was
# stranded — and every later pass of campaign.sh tripped its on-main guard and logged
# "on 'HEAD' not main", a symptom four days downstream of its cause. That is how Loam
# lost passes 2-8 on 2026-07-31. campaign.sh:169 (`safe_pull_rebase`) fixed this class
# for the physics lane; this script is its sibling in the same clone and regressed it.
# pot.json is regenerated by BOTH boxes, so the conflict recurs by construction.
#
# This is deliberately the strict half of campaign.sh's version: it does not attempt
# `resolve_by_regeneration` (that helper is campaign.sh's own and rebuilding the feeds
# needs the `lab` CLI). It fails loudly, leaves the clone usable, and lets the caller
# skip the slot rather than pretend it synced.
safe_pull_rebase(){
  local out rc
  out="$(git pull --rebase --autostash 2>&1)"; rc=$?
  [ "$rc" -eq 0 ] && return 0
  echo "$(date -Is) pull --rebase FAILED rc=$rc: $(printf '%s' "$out" | tail -3 | tr '\n' ' ')" >>"$log"
  if [ -d .git/rebase-merge ] || [ -d .git/rebase-apply ]; then
    if git rebase --abort >>"$log" 2>&1; then
      echo "$(date -Is) rebase aborted, clone restored to '$(git rev-parse --abbrev-ref HEAD 2>/dev/null)'" >>"$log"
    else
      echo "$(date -Is) rebase abort FAILED — clone is STRANDED, manual repair required" >>"$log"
    fi
  fi
  return 1
}

if ! safe_pull_rebase; then
  echo "$(date -Is) slot SKIPPED — refusing to hunt against an unsynced clone" >>"$log"
  exit 1
fi

echo "$(date -Is) slot start — sector $sector" >>"$log"

# THE WINDOW RULE. There is ONE log file per sector per day and all four slots
# append to it, so anything read back out of it has to be scoped to THIS run.
# Read the whole file and a crashed slot 2 inherits slot 1's "receipt -> " line,
# republishing a receipt that is already committed; read a fixed `tail -5` window
# and this run's grade line is invisible the moment anything prints after it.
# Remember where this run starts and read only from there.
log_mark=$(wc -l <"$log" 2>/dev/null || echo 0)
PYTHONPATH=src "$PY" scripts/a05_hunt.py \
  --sector "$sector" --n 200 --minutes 100 >>"$log" 2>&1
rc=$?
echo "$(date -Is) runner exit $rc" >>"$log"
run_log="$(tail -n +$((log_mark + 1)) "$log")"

# THE STAGING RULE. Stage the receipt the RUNNER says it wrote, read back from its
# own "receipt -> PATH" line. This was once a glob, `hunt-*-s${sector}.json`, written
# before the runner gained a collision-proof -HHMM suffix on every receipt after the
# day's first: the glob then matched slot 1 and nothing else, so slots 2-4 wrote
# receipts that were never staged and `git commit` reported "nothing to commit" and
# exited 0 — a silent failure under a green unit. Two graded receipts stranded that
# way before it was caught. A path the producer PRINTS cannot drift out of sync with
# the producer's naming; a glob written from memory always can.
receipt="$(printf '%s\n' "$run_log" | sed -n 's|^receipt -> ||p' | tail -1)"

# THE GATE. Publishing needs two POSITIVE proofs, never the absence of a negative.
# It used to need neither: `rc` was captured on the line after the runner and never
# read again, and success was inferred from `tail -5 "$log"` NOT matching
# `check_a05: None|False`. A crash between the receipt write (a05_hunt.py:296) and
# the grade print satisfies that gate perfectly — a complete-looking receipt on
# disk, no failure string anywhere — and publishes an ungraded receipt alongside a
# pot.json the dead run never refreshed. CI recomputes `pot == hunt_block()` from
# the committed set and goes red in the producer's own commit: the realized
# 2026-08-15 class. Absence is what a crash, a truncated log, a scrolled-away line
# and a renamed grade token ALL look like.
#
# Proof 1: the runner exited 0.
if [ "$rc" -ne 0 ]; then
  echo "$(date -Is) runner failed rc=$rc — nothing of this run is published" >>"$log"
  quarantine_receipt
  restore_pot
  exit "$rc"
fi
if [ -z "$receipt" ] || [ ! -f "$receipt" ]; then
  echo "$(date -Is) no receipt path in this run's log — nothing staged" >>"$log"
  restore_pot
  exit 1
fi
# Proof 2: this run printed `check_a05: True`. None (a control failed, so the FAPs
# mean nothing) and False (a real failure) stay local with the log — win's contract.
if ! printf '%s\n' "$run_log" | grep -q '^check_a05: True'; then
  echo "$(date -Is) no positive grade in this run's log — receipt NOT pushed" >>"$log"
  quarantine_receipt
  restore_pot
  exit 0
fi

stem="$(basename "$receipt" .json)"

# A lead's rendered dossier is named <receipt stem>-tic<id>.html and is cited by the
# receipt that ships it, so it has to travel WITH that receipt. The 2026-08-18 lead
# (TIC 287328866) pushed its receipt and left its dossier sitting untracked.
if ! git add -- pot.json "$receipt" "reports/hunts/dossiers/${stem}"-tic*.html 2>>"$log"; then
  restore_pot
  exit 1
fi
# THE COMMIT RULE. This was `git commit … || exit 0  # nothing new to commit`, which
# read EVERY commit failure as the benign one. Only one of them is benign.
# campaign.sh runs in this same clone in these same hours with no git-level lock
# between the two lanes; lose the .git/index.lock race to it and the commit fails
# with the receipt STAGED — and a staged index is one of the three conditions
# campaign.sh itself refuses to run against, so one lost race silently halts the
# OTHER lane until a human notices. Two failures, two branches, two exit codes.
#
# Contention is transient by construction (the other lane finishes its own commit
# in seconds), so retry a bounded number of times first. Bounded and lock-free:
# this waits on nothing it could deadlock against. The real root cause — two lanes,
# one clone, no shared lock — needs campaign.sh to take the same lock and is not
# closed here; see docs/gauntlet/evidence/LANE2-AUTOMATION.md.
commit_msg="a05: hunt receipt sector ${sector} $(date +%F) (loam slot)

Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>"
tries="${LAB_HUNT_COMMIT_TRIES:-4}"
retry_sleep="${LAB_HUNT_COMMIT_SLEEP:-5}"
while : ; do
  commit_mark=$(wc -l <"$log" 2>/dev/null || echo 0)
  git commit -q -m "$commit_msg" >>"$log" 2>&1
  crc=$?
  [ "$crc" -eq 0 ] && break
  tries=$((tries - 1))
  [ "$tries" -le 0 ] && break
  tail -n +$((commit_mark + 1)) "$log" | grep -q 'index\.lock' || break
  echo "$(date -Is) commit blocked by index.lock — retrying in ${retry_sleep}s ($tries left)" >>"$log"
  sleep "$retry_sleep"
done

if [ "$crc" -ne 0 ]; then
  # Ask the index which failure this was. Nothing staged means the receipt was
  # already published (a re-run of a finished slot) — quiet success, the case the
  # old `|| exit 0` was written for. Anything staged means the commit really failed.
  if git diff --cached --quiet --; then
    echo "$(date -Is) nothing new to commit — this receipt is already published" >>"$log"
    restore_pot
    exit 0
  fi
  echo "$(date -Is) commit FAILED rc=$crc with changes staged — unstaging so the campaign lane is not blocked" >>"$log"
  git reset -q -- pot.json "$receipt" "reports/hunts/dossiers/${stem}"-tic*.html >>"$log" 2>&1
  quarantine_receipt
  restore_pot
  exit 1
fi

if ! safe_pull_rebase; then
  # The receipt is COMMITTED locally, so this clone's pot and its receipt set still
  # agree — nothing here is red, it is just unpublished. The commit stays; the next
  # slot's pre-hunt pull is the retry, and it refuses to hunt until this resolves.
  echo "$(date -Is) receipt committed but NOT pushed — the next slot's pull retries it" >>"$log"
  exit 1
fi
if git push -q >>"$log" 2>&1; then
  echo "$(date -Is) receipt pushed" >>"$log"
else
  echo "$(date -Is) push FAILED — receipt committed locally, not published" >>"$log"
  exit 1
fi
