#!/usr/bin/env python3
"""Regenerate the journal article's terms table from the run log.

TARGETS entries.yaml, NOT the rendered page. journal/<slug>/index.html is
GENERATED by gen-journal.mjs from journal/entries.yaml, so anything written
directly into the page is deleted by the next build without a word. That is how
work quietly disappears. Edit the source; regenerate; verify with
`node scripts/gen-journal.mjs --check`.

Same rule as the OEIS package: no integer is retyped between the computation and
anything a reader sees. The article carries marker comments and this rewrites
what is between them, so publishing at the end of a run is one command rather
than a careful afternoon with a keyboard.

Refuses for the same reasons `c03_submission.py` refuses — a divergence between
the two methods, a value contradicting a published one, or a gap in the log. An
article is a publication; it gets the same gate the submission does.

Usage:  python3 scripts/c03_article_terms.py <run.log> <entries.yaml>
        then: (cd <site> && npm run gen:journal && node scripts/gen-journal.mjs --check)
"""
from __future__ import annotations

import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from c03_submission import PUBLISHED, parse_log  # noqa: E402

WORDS = {7: "Seven", 8: "Eight", 9: "Nine", 10: "Ten", 11: "Eleven",
         12: "Twelve", 13: "Thirteen", 14: "Fourteen", 15: "Fifteen",
         16: "Sixteen", 17: "Seventeen", 18: "Eighteen", 19: "Nineteen",
         20: "Twenty"}


def render_table(rows, new_n):
    out = ['<table class="assay-table">',
           '      <thead><tr><th>n</th><th>Method A — enumeration</th>'
           '<th>Method B — the conjecture</th><th></th></tr></thead>',
           '      <tbody>']
    for n in new_n:
        r = rows[n]
        out.append(f'        <tr><td class="num">{n}</td>'
                   f'<td class="num">{r["brute"]}</td>'
                   f'<td class="num">{r["conj"]}</td>'
                   f'<td class="v-pass">agree</td></tr>')
    out.append('      </tbody>')
    out.append('    </table>')
    return "\n      ".join(out[:1]) + "\n" + "\n".join(out[1:])


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    log, article = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    if article.name != "entries.yaml":
        print(f"REFUSING: {article} is not entries.yaml. The rendered page is a\n"
              "  build artifact and editing it is a change that the next\n"
              "  `npm run gen:journal` silently discards.", file=sys.stderr)
        return 2
    rows = parse_log(log)
    if not rows:
        print("no parseable rows", file=sys.stderr)
        return 2

    problems = []
    lo, hi = min(rows), max(rows)
    gaps = [n for n in range(lo, hi + 1) if n not in rows]
    if gaps:
        problems.append(f"log has gaps at n={gaps}")
    for n, r in sorted(rows.items()):
        if r["brute"] != r["conj"]:
            problems.append(f"n={n}: methods DISAGREE ({r['brute']} vs {r['conj']})")
        if r["ref"] is not None and r["ref"] != r["brute"]:
            problems.append(f"n={n}: contradicts the reference {r['ref']}")
    for i, want in enumerate(PUBLISHED, start=1):
        got = rows.get(i, {}).get("brute")
        if got is None:
            problems.append(f"n={i} of the published {len(PUBLISHED)} was never recomputed")
        elif got != want:
            problems.append(f"n={i}: recomputed {got}, entry publishes {want}")
    if problems:
        print("REFUSING to update the article:", file=sys.stderr)
        for p in problems:
            print("  -", p, file=sys.stderr)
        return 1

    new_n = [n for n in sorted(rows) if n > len(PUBLISHED)]
    if not new_n:
        print("no new terms in this log — nothing to publish", file=sys.stderr)
        return 1

    html = article.read_text()
    word = WORDS.get(len(new_n), str(len(new_n)))
    sentence = (
        f'<p>{word} terms so far that the entry did not carry this morning, each '
        f'one produced by method A and confirmed by method B, at n={min(new_n)} '
        f'through n={max(new_n)}.</p>')
    html = re.sub(r"<!-- TERMS:COUNT:BEGIN -->.*?<!-- TERMS:COUNT:END -->",
                  f"<!-- TERMS:COUNT:BEGIN -->\n      {sentence}\n      "
                  "<!-- TERMS:COUNT:END -->", html, flags=re.S)
    html = re.sub(r"<!-- TERMS:TABLE:BEGIN -->.*?<!-- TERMS:TABLE:END -->",
                  "<!-- TERMS:TABLE:BEGIN -->\n      "
                  + render_table(rows, new_n).replace("\n", "\n  ")
                  + "\n      <!-- TERMS:TABLE:END -->", html, flags=re.S)
    article.write_text(html)
    print(f"updated {article.name}: {len(new_n)} new terms "
          f"(n={min(new_n)}..{max(new_n)}), {len(PUBLISHED)} published reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
